### ISSUE TITLE
Extend Symfony & existing synapse constraints

### ISSUE THREAD

**Issue by baohx2000** [synapsestudios/synapse-base#214] opened 2015-05-15 23:26 UTC
### Acceptance Criteria
1. Extensions of all Symfony constraints exist at `\Synapse\Validation\NewConstraints\*`
1. Copies of existing `\Synapse\Validator\Constraints\*` classes exist in above namespace with constant messages.
1. Existing `\Synapse\Validator\Constraints\*` classes marked as deprecated via docblock, with the explanation that upon the next major revision to synapse-base, `NewConstraints` will become `Constraints` and the legacy `Constraints` classes would go away.

### Tasks
- Create synapse-base copies of all the Symfony validator classes with constant-y validation messages
- Create `NewConstraints` copies of all synapse-base constraints with constant-y validation messages

**Comment by baohx2000** [comment] 2015-05-15 23:26
:sunny: :arrow_double_down:

**Comment by paulstatezny** [comment] 2015-05-18 22:20
I feel like the Symfony constraint wrappers should just go in `\Synapse\Validator\Constraints\*`, to make it more future-compatible.

Also, I feel like we should just go ahead and make the change to the current constraints (to more constant-ey messages) and just major-version bump the package.

As long as it's going to be done in the future and people are going to have to upgrade, what's the purpose of not just doing that now?

**Comment by paulstatezny** [comment] 2015-05-18 22:20
:interrobang:

**Comment by paulstatezny** [comment] 2015-05-18 22:22
As long as we put notices and instructions in the UPGRADE_GUIDE, there's no harm for projects that want to upgrade. It would be helpful to specify the old messages in the upgrade guide so old projects could add them in manually if desired.

**Comment by baohx2000** [comment] 2015-05-18 23:16
I'm okay with that as long as everyone else is.

**Comment by tdboone** [comment] 2015-05-22 22:44
:boom: duplicate of #202

**Closed by tdboone** 2015-05-22 22:44 UTC
Labels: C-Low, P-Low, S-Open, T-Story
